spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_library?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

logging:
  level:
    root: warn
    com.chilly: info
  file:
    path: log/examlibrary-pro.log
server:
  port: 80
